# Generated by Django 5.0.7 on 2025-12-17 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('sample_type_id', models.CharField(max_length=50)),
                ('parameters', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('lab_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('COLLECTED', 'Collected'), ('ANALYZED', 'Analyzed'), ('VERIFIED', 'Verified')], default='REGISTERED', max_length=20)),
                ('results', models.JSONField(default=dict)),
                ('payment', models.JSONField(default=dict)),
                ('referred_by', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('ai_interpretation', models.TextField(blank=True)),
                ('collected_samples', models.JSONField(default=list)),
                ('phlebotomy_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tests', models.ManyToManyField(related_name='requests', to='api.labtest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
