# Generated by Django 5.0.7 on 2025-12-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tube_color', models.CharField(max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
