# Generated by Django 5.0.7 on 2025-12-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sampletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrequest',
            name='collected_samples',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='payment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='results',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
